type IoTrafficLightState = struct {
  current_light: str,
  all_users: vec struct { actor_id, str },
};

type TrafficLightEvent = enum {
  Green,
  Yellow,
  Red,
};

constructor {
  New : ();
};

service Query {
  query TrafficLight : () -> IoTrafficLightState;
};

service TrafficLight {
  Green : () -> TrafficLightEvent;
  Red : () -> TrafficLightEvent;
  Yellow : () -> TrafficLightEvent;
};

